// import React, { useState, useEffect } from 'react';
// import {
//   Dialog,
//   DialogTitle,
//   DialogContent,
//   DialogActions,
//   Box,
//   Grid,
//   TextField,
//   FormControl,
//   InputLabel,
//   Select,
//   MenuItem,
//   Button,
//   Typography,
//   FormHelperText,
//   CircularProgress,
//   Alert,
//   Card,
//   CardContent,
//   IconButton
// } from '@mui/material';
// import {
//   Close,
//   Save,
//   Inventory,
//   Info,
//   BatchPrediction
// } from '@mui/icons-material';
// import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
// import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
// import { DatePicker } from '@mui/x-date-pickers/DatePicker';

// const MaterialRIForm = ({ 
//   open, 
//   onClose, 
//   transaction, 
//   viewMode = false, 
//   onSave, 
//   loading = false,
//   materials = [],
//   availableBatches = [],
//   onFetchBatches
// }) => {
//   const [formData, setFormData] = useState({
//     Material: '',
//     Activity: 'Receive',
//     Quantity: '',
//     Unit: '',
//     Batch: '',
//     Stock: '',
//     Note: '',
//     DocNo: '',
//     Date: new Date()
//   });

//   const [errors, setErrors] = useState({});
//   const [selectedMaterial, setSelectedMaterial] = useState(null);
//   const [showBatchWarning, setShowBatchWarning] = useState(false);

//   // Initialize form when transaction or materials change
//   useEffect(() => {
//     if (transaction) {
//       // Edit mode - populate form with transaction data
//       const materialId = transaction.Material?._id || transaction.Material;
//       const material = materials.find(m => m.id === materialId);
      
//       setFormData({
//         Material: materialId || '',
//         Activity: transaction.Activity || 'Receive',
//         Quantity: transaction.Quantity || '',
//         Unit: transaction.Unit || (material ? material.unit : ''),
//         Batch: transaction.Batch || '',
//         Stock: transaction.Stock || '',
//         Note: transaction.Note || '',
//         DocNo: transaction.DocNo || '',
//         Date: transaction.Date ? new Date(transaction.Date) : new Date()
//       });
      
//       setSelectedMaterial(material);
      
//       // If it's an issue transaction, fetch available batches
//       if (transaction.Activity === 'Issue' && materialId) {
//         onFetchBatches(materialId);
//       }
//     } else {
//       // Add mode - reset form
//       setFormData({
//         Material: '',
//         Activity: 'Receive',
//         Quantity: '',
//         Unit: '',
//         Batch: '',
//         Stock: '',
//         Note: '',
//         DocNo: '',
//         Date: new Date()
//       });
//       setSelectedMaterial(null);
//       setShowBatchWarning(false);
//     }
//     setErrors({});
//   }, [transaction, materials, open]);

//   // Update selected material when Material changes
//   useEffect(() => {
//     if (formData.Material) {
//       const material = materials.find(m => m.id === formData.Material);
//       setSelectedMaterial(material);
      
//       // Auto-populate unit from selected material
//       if (material) {
//         setFormData(prev => ({
//           ...prev,
//           Unit: material.unit || prev.Unit
//         }));

//         // Fetch available batches if activity is Issue
//         if (formData.Activity === 'Issue') {
//           onFetchBatches(formData.Material);
//         }
//       }
//     } else {
//       setSelectedMaterial(null);
//       setShowBatchWarning(false);
//     }
//   }, [formData.Material, materials]);

//   // Handle activity change
//   useEffect(() => {
//     if (formData.Activity === 'Receive') {
//       // Clear batch for receive activities (auto-generated by backend)
//       setFormData(prev => ({
//         ...prev,
//         Batch: ''
//       }));
//       setShowBatchWarning(false);
//     } else if (formData.Activity === 'Issue' && formData.Material) {
//       // Fetch batches for issue activities
//       onFetchBatches(formData.Material);
//     }
//   }, [formData.Activity, formData.Material]);

//   const handleChange = (field) => (event) => {
//     const value = event.target ? event.target.value : event;
    
//     setFormData(prev => ({
//       ...prev,
//       [field]: value
//     }));

//     // Clear error when user starts typing
//     if (errors[field]) {
//       setErrors(prev => ({
//         ...prev,
//         [field]: ''
//       }));
//     }

//     // If material changes, clear material-related errors and fetch batches for issue
//     if (field === 'Material' && errors.Material) {
//       setErrors(prev => ({
//         ...prev,
//         Material: ''
//       }));
      
//       if (formData.Activity === 'Issue' && value) {
//         onFetchBatches(value);
//       }
//     }

//     // If activity changes, handle batch logic
//     if (field === 'Activity') {
//       if (value === 'Receive') {
//         setFormData(prev => ({
//           ...prev,
//           Batch: '' // Clear batch for receive
//         }));
//         setShowBatchWarning(false);
//       } else if (value === 'Issue' && formData.Material) {
//         onFetchBatches(formData.Material);
//       }
//     }
//   };

//   const validateForm = () => {
//     const newErrors = {};

//     // Required field validation
//     if (!formData.Material) {
//       newErrors.Material = 'Material selection is required';
//     }

//     if (!formData.Quantity || formData.Quantity <= 0) {
//       newErrors.Quantity = 'Valid quantity is required';
//     }

//     if (!formData.Unit?.trim()) {
//       newErrors.Unit = 'Unit is required';
//     }

//     if (!formData.Date) {
//       newErrors.Date = 'Date is required';
//     }

//     // Restrict future dates
//     const inputDate = new Date(formData.Date);
//     const today = new Date();
//     today.setHours(0, 0, 0, 0);
    
//     if (inputDate > today) {
//       newErrors.Date = 'Future dates are not allowed';
//     }

//     // Activity-specific validation
//     if (formData.Activity === 'Issue') {
//       // Batch validation for Issue
//       if (!formData.Batch?.trim()) {
//         newErrors.Batch = 'Batch selection is required for Issue activities';
//       } else {
//         // Check if selected batch has sufficient stock
//         const selectedBatch = availableBatches.find(batch => batch._id === formData.Batch);
//         if (selectedBatch) {
//           if (selectedBatch.stock < parseFloat(formData.Quantity)) {
//             newErrors.Quantity = `Insufficient stock in batch. Available: ${selectedBatch.stock}`;
//             setShowBatchWarning(true);
//           } else {
//             setShowBatchWarning(false);
//           }
//         }
//       }
//     }

//     // For Receive activities, ensure batch is empty (auto-generated by backend)
//     if (formData.Activity === 'Receive' && formData.Batch?.trim()) {
//       newErrors.Batch = 'Batch should be empty for Receive activities (auto-generated)';
//     }

//     setErrors(newErrors);
//     return Object.keys(newErrors).length === 0;
//   };

//   const handleSubmit = (e) => {
//     e.preventDefault();
    
//     if (!validateForm()) {
//       return;
//     }

//     // Prepare data for API - include ALL fields from schema
//     const submissionData = {
//       Date: formData.Date.toISOString().split('T')[0], // Format as YYYY-MM-DD
//       Activity: formData.Activity,
//       Material: formData.Material,
//       Quantity: parseFloat(formData.Quantity),
//       Unit: formData.Unit,
//       Stock: formData.Stock ? parseFloat(formData.Stock) : 0, // Include Stock field
//       Note: formData.Note,
//       DocNo: formData.DocNo
//     };

//     // Only include Batch for Issue activities (for Receive, backend will auto-generate)
//     if (formData.Activity === 'Issue') {
//       submissionData.Batch = formData.Batch;
//     }

//     console.log('📤 Submitting form data:', submissionData);
//     onSave(submissionData);
//   };

//   const handleClose = () => {
//     onClose();
//   };

//   const formatNumber = (number) => {
//     return number ? number.toLocaleString() : '0';
//   };

//   // Get selected batch details
//   const getSelectedBatchDetails = () => {
//     if (formData.Activity === 'Issue' && formData.Batch) {
//       return availableBatches.find(batch => batch._id === formData.Batch);
//     }
//     return null;
//   };

//   const selectedBatch = getSelectedBatchDetails();

//   // Generate batch preview for Receive activities
//   const getBatchPreview = () => {
//     if (formData.Activity === 'Receive' && selectedMaterial && formData.Date) {
//       const date = new Date(formData.Date);
//       const day = String(date.getDate()).padStart(2, '0');
//       const month = String(date.getMonth() + 1).padStart(2, '0');
//       const year = String(date.getFullYear()).slice(-2);
//       return `${selectedMaterial.code}-${day}${month}${year}`;
//     }
//     return null;
//   };

//   const batchPreview = getBatchPreview();

//   return (
//     <Dialog 
//       open={open} 
//       onClose={handleClose}
//       maxWidth="md"
//       fullWidth
//       PaperProps={{
//         sx: { borderRadius: 2 }
//       }}
//     >
//       <DialogTitle sx={{ 
//         bgcolor: 'primary.main', 
//         color: 'white',
//         display: 'flex',
//         justifyContent: 'space-between',
//         alignItems: 'center'
//       }}>
//         <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
//           <Inventory />
//           <Typography variant="h6">
//             {viewMode ? 'View' : transaction ? 'Edit' : 'Add'} Material Transaction
//           </Typography>
//         </Box>
//         <IconButton onClick={handleClose} sx={{ color: 'white' }}>
//           <Close />
//         </IconButton>
//       </DialogTitle>

//       <DialogContent sx={{ p: 3 }}>
//         {materials.length === 0 && (
//           <Alert severity="warning" sx={{ mb: 2 }}>
//             No active materials available. Please add materials to the database first.
//           </Alert>
//         )}

//         <LocalizationProvider dateAdapter={AdapterDateFns}>
//           <Box component="form" onSubmit={handleSubmit} noValidate>
//             <Grid container spacing={3}>
//               {/* Material Selection */}
//               <Grid item xs={12} md={6}>
//                 <FormControl 
//                   fullWidth 
//                   error={!!errors.Material}
//                   required
//                   disabled={viewMode || loading || materials.length === 0}
//                 >
//                   <InputLabel id="material-select-label">Material *</InputLabel>
//                   <Select
//                     labelId="material-select-label"
//                     value={formData.Material}
//                     label="Material *"
//                     onChange={handleChange('Material')}
//                   >
//                     <MenuItem value="">
//                       <em>Select Material</em>
//                     </MenuItem>
//                     {materials.map((material) => (
//                       <MenuItem key={material.id} value={material.id}>
//                         <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
//                           <Typography variant="body1">
//                             {material.name}
//                           </Typography>
//                           <Typography variant="body2" color="text.secondary" sx={{ ml: 2 }}>
//                             {material.code}
//                           </Typography>
//                         </Box>
//                       </MenuItem>
//                     ))}
//                   </Select>
//                   {errors.Material && (
//                     <FormHelperText>{errors.Material}</FormHelperText>
//                   )}
//                 </FormControl>
//               </Grid>

//               {/* Activity */}
//               <Grid item xs={12} md={6}>
//                 <FormControl 
//                   fullWidth 
//                   required
//                   disabled={viewMode || loading || !!transaction}
//                 >
//                   <InputLabel id="activity-select-label">Activity *</InputLabel>
//                   <Select
//                     labelId="activity-select-label"
//                     value={formData.Activity}
//                     label="Activity *"
//                     onChange={handleChange('Activity')}
//                   >
//                     <MenuItem value="Receive">Receive</MenuItem>
//                     <MenuItem value="Issue">Issue</MenuItem>
//                   </Select>
//                 </FormControl>
//               </Grid>

//               {/* Selected Material Info */}
//               {selectedMaterial && (
//                 <Grid item xs={12}>
//                   <Card variant="outlined" sx={{ bgcolor: 'background.default' }}>
//                     <CardContent>
//                       <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
//                         <Info color="primary" />
//                         Selected Material Details
//                       </Typography>
//                       <Grid container spacing={2}>
//                         <Grid item xs={6} sm={3}>
//                           <Typography variant="body2" color="text.secondary">
//                             Code:
//                           </Typography>
//                           <Typography variant="body1" fontWeight="medium">
//                             {selectedMaterial.code}
//                           </Typography>
//                         </Grid>
//                         <Grid item xs={6} sm={3}>
//                           <Typography variant="body2" color="text.secondary">
//                             Unit:
//                           </Typography>
//                           <Typography variant="body1">
//                             {selectedMaterial.unit}
//                           </Typography>
//                         </Grid>
//                         {formData.Activity === 'Receive' && batchPreview && (
//                           <Grid item xs={12} sm={6}>
//                             <Alert severity="info" sx={{ py: 1 }}>
//                               <Typography variant="body2">
//                                 <strong>Batch Preview:</strong> {batchPreview}
//                               </Typography>
//                               <Typography variant="caption">
//                                 Batch will be auto-generated in format: MaterialCode-DDMMYY
//                               </Typography>
//                             </Alert>
//                           </Grid>
//                         )}
//                       </Grid>
//                     </CardContent>
//                   </Card>
//                 </Grid>
//               )}

//               {/* Batch Selection for Issue */}
//               {formData.Activity === 'Issue' && formData.Material && (
//                 <Grid item xs={12}>
//                   <FormControl 
//                     fullWidth 
//                     error={!!errors.Batch}
//                     required
//                     disabled={viewMode || loading}
//                   >
//                     <InputLabel id="batch-select-label">Select Batch *</InputLabel>
//                     <Select
//                       labelId="batch-select-label"
//                       value={formData.Batch}
//                       label="Select Batch *"
//                       onChange={handleChange('Batch')}
//                     >
//                       <MenuItem value="">
//                         <em>Select Available Batch</em>
//                       </MenuItem>
//                       {availableBatches.map((batch) => (
//                         <MenuItem key={batch._id} value={batch._id}>
//                           <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
//                             <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
//                               <BatchPrediction fontSize="small" />
//                               <Typography variant="body1">
//                                 {batch._id}
//                               </Typography>
//                             </Box>
//                             <Typography 
//                               variant="body2" 
//                               color={batch.stock > 0 ? 'success.main' : 'error.main'}
//                               sx={{ ml: 2 }}
//                             >
//                               Stock: {formatNumber(batch.stock)}
//                             </Typography>
//                           </Box>
//                         </MenuItem>
//                       ))}
//                     </Select>
//                     {errors.Batch && (
//                       <FormHelperText>{errors.Batch}</FormHelperText>
//                     )}
//                     {availableBatches.length === 0 && formData.Material && (
//                       <FormHelperText error>
//                         No batches with available stock for this material
//                       </FormHelperText>
//                     )}
//                   </FormControl>
//                 </Grid>
//               )}

//               {/* Selected Batch Info for Issue */}
//               {formData.Activity === 'Issue' && selectedBatch && (
//                 <Grid item xs={12}>
//                   <Card variant="outlined" sx={{ 
//                     borderColor: showBatchWarning ? 'error.main' : 'primary.main', 
//                     bgcolor: showBatchWarning ? 'error.light' : 'primary.light' 
//                   }}>
//                     <CardContent>
//                       <Typography variant="subtitle1" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
//                         <BatchPrediction />
//                         Selected Batch: {selectedBatch._id}
//                       </Typography>
//                       <Typography variant="body2">
//                         Available Stock: <strong>{formatNumber(selectedBatch.stock)}</strong> {formData.Unit}
//                       </Typography>
//                       {selectedBatch.lastActivity && (
//                         <Typography variant="caption" display="block" color="text.secondary">
//                           Last Activity: {selectedBatch.lastActivity} on {new Date(selectedBatch.lastDate).toLocaleDateString()}
//                         </Typography>
//                       )}
//                     </CardContent>
//                   </Card>
//                 </Grid>
//               )}

//               {/* Quantity and Unit */}
//               <Grid item xs={12} sm={6}>
//                 <TextField
//                   fullWidth
//                   label="Quantity *"
//                   type="number"
//                   value={formData.Quantity}
//                   onChange={handleChange('Quantity')}
//                   error={!!errors.Quantity}
//                   helperText={errors.Quantity}
//                   disabled={viewMode || loading}
//                   inputProps={{ 
//                     min: 0.01,
//                     step: 0.01
//                   }}
//                   required
//                 />
//               </Grid>

//               <Grid item xs={12} sm={6}>
//                 <TextField
//                   fullWidth
//                   label="Unit *"
//                   value={formData.Unit}
//                   onChange={handleChange('Unit')}
//                   error={!!errors.Unit}
//                   helperText={errors.Unit}
//                   disabled={viewMode || loading}
//                   required
//                 />
//               </Grid>

//               {/* Stock Field - Maintained from Schema */}
//               <Grid item xs={12} sm={6}>
//                 <TextField
//                   fullWidth
//                   label="Stock"
//                   type="number"
//                   value={formData.Stock}
//                   onChange={handleChange('Stock')}
//                   disabled={viewMode || loading}
//                   inputProps={{ 
//                     min: 0,
//                     step: 0.01
//                   }}
//                   helperText="Current stock level"
//                 />
//               </Grid>

//               {/* Transaction Date */}
//               <Grid item xs={12} sm={6}>
//                 <DatePicker
//                   label="Transaction Date *"
//                   value={formData.Date}
//                   onChange={handleChange('Date')}
//                   disabled={viewMode || loading}
//                   maxDate={new Date()} // Prevent future dates
//                   renderInput={(params) => (
//                     <TextField
//                       {...params}
//                       fullWidth
//                       error={!!errors.Date}
//                       helperText={errors.Date || 'Future dates are not allowed'}
//                       required
//                     />
//                   )}
//                 />
//               </Grid>

//               {/* Document Number */}
//               <Grid item xs={12} sm={6}>
//                 <TextField
//                   fullWidth
//                   label="Document No"
//                   value={formData.DocNo}
//                   onChange={handleChange('DocNo')}
//                   disabled={viewMode || loading}
//                   placeholder="Optional document reference"
//                 />
//               </Grid>

//               {/* Notes */}
//               <Grid item xs={12}>
//                 <TextField
//                   fullWidth
//                   label="Notes"
//                   multiline
//                   rows={3}
//                   value={formData.Note}
//                   onChange={handleChange('Note')}
//                   disabled={viewMode || loading}
//                   placeholder="Additional notes or comments..."
//                 />
//               </Grid>

//               {/* Summary Alert */}
//               {formData.Material && formData.Quantity && !errors.Quantity && (
//                 <Grid item xs={12}>
//                   <Alert 
//                     severity={
//                       formData.Activity === 'Receive' ? 'success' : 
//                       showBatchWarning ? 'warning' : 'info'
//                     }
//                   >
//                     <Typography variant="body2">
//                       <strong>Summary:</strong> {formData.Activity} {formatNumber(formData.Quantity)} {formData.Unit} of {selectedMaterial?.name}
//                       {formData.Activity === 'Issue' && selectedBatch && (
//                         <span> from batch {selectedBatch._id}</span>
//                       )}
//                       {formData.Activity === 'Receive' && batchPreview && (
//                         <span> (Batch: {batchPreview})</span>
//                       )}
//                       {showBatchWarning && (
//                         <span> - <strong>Warning: Insufficient stock!</strong></span>
//                       )}
//                     </Typography>
//                   </Alert>
//                 </Grid>
//               )}
//             </Grid>
//           </Box>
//         </LocalizationProvider>
//       </DialogContent>

//       <DialogActions sx={{ p: 3, gap: 1 }}>
//         <Button 
//           onClick={handleClose}
//           disabled={loading}
//           variant="outlined"
//         >
//           Cancel
//         </Button>
//         {!viewMode && (
//           <Button
//             type="submit"
//             variant="contained"
//             onClick={handleSubmit}
//             disabled={loading || materials.length === 0 || showBatchWarning}
//             startIcon={loading ? <CircularProgress size={20} /> : <Save />}
//           >
//             {loading ? 'Saving...' : transaction ? 'Update' : 'Save'} Transaction
//           </Button>
//         )}
//       </DialogActions>
//     </Dialog>
//   );
// };

// export default MaterialRIForm;